# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color:rgb(252, 234, 255);\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cosmetics_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.cosmetics_label.setGeometry(QtCore.QRect(50, 20, 221, 211))
        self.cosmetics_label.setText("")
        self.cosmetics_label.setPixmap(QtGui.QPixmap("static/IMG-20240730-WA0109.jpg"))
        self.cosmetics_label.setObjectName("cosmetics_label")
        self.nails_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.nails_label.setGeometry(QtCore.QRect(50, 330, 221, 201))
        self.nails_label.setText("")
        self.nails_label.setPixmap(QtGui.QPixmap("static/IMG-20240730-WA0112.jpg"))
        self.nails_label.setObjectName("nails_label")
        self.hair_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.hair_label.setGeometry(QtCore.QRect(540, 20, 221, 221))
        self.hair_label.setText("")
        self.hair_label.setPixmap(QtGui.QPixmap("static/IMG-20240730-WA0110.jpg"))
        self.hair_label.setObjectName("hair_label")
        self.cosmeticsBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.cosmeticsBtn.setGeometry(QtCore.QRect(120, 190, 75, 24))
        self.cosmeticsBtn.setObjectName("cosmeticsBtn")
        self.nailsBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.nailsBtn.setGeometry(QtCore.QRect(130, 490, 75, 24))
        self.nailsBtn.setObjectName("nailsBtn")
        self.meetUsBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.meetUsBtn.setGeometry(QtCore.QRect(290, 250, 241, 51))
        self.meetUsBtn.setObjectName("meetUsBtn")
        self.productsBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.productsBtn.setGeometry(QtCore.QRect(360, 320, 241, 51))
        self.productsBtn.setObjectName("productsBtn")
        self.pricesBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pricesBtn.setGeometry(QtCore.QRect(440, 390, 241, 51))
        self.pricesBtn.setObjectName("pricesBtn")
        self.apptBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.apptBtn.setGeometry(QtCore.QRect(510, 470, 241, 51))
        self.apptBtn.setObjectName("apptBtn")
        self.hairBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.hairBtn.setGeometry(QtCore.QRect(630, 190, 75, 24))
        self.hairBtn.setObjectName("hairBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cosmeticsBtn.setText(_translate("MainWindow", "Cosmetics"))
        self.nailsBtn.setText(_translate("MainWindow", "Nails"))
        self.meetUsBtn.setText(_translate("MainWindow", "Meet The Team"))
        self.productsBtn.setText(_translate("MainWindow", "Our products"))
        self.pricesBtn.setText(_translate("MainWindow", "Prices"))
        self.apptBtn.setText(_translate("MainWindow", "Book an appointment"))
        self.hairBtn.setText(_translate("MainWindow", "Hair"))
